name: Android App
on:
  push:
    paths-ignore:
     - 'README.md'
  pull_request:
    paths-ignore:
     - 'README.md'
  workflow_dispatch:
    inputs:
      version:
        description: dummy
        default: dummy

jobs:
  update-nightly-tag:
    name: Update nightly release tag
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    permissions:
        contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Move nightly tag to head for nightly release
        run: git tag -f nightly && git push origin nightly -f

  android-app:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        api-level: [35, 33, 29, 21]
    permissions:
      contents: write
    if: ${{ true }}
    steps:
      - uses: actions/checkout@v4

      - name: install deps
        run: |
          sudo apt-get update && \
          sudo DEBIAN_FRONTEND=noninteractive \
          apt-get install -y --no-install-recommends \
          fonts-freefont-otf \
          adb \
          ghostscript \
          imagemagick \
          ca-certificates

      - name: check imagemagick
        run: |
          convert -list font || echo "NO ERR"

      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: |
            17

      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: test java1
        run:  |
              pwd
              type java
              echo "===========1========="
              java -version || exit 0
              echo "===========2========="

      - name: android test
        timeout-minutes: 30
        continue-on-error: true
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          profile: Nexus 6
          arch: x86_64
          ndk: 21.0.6113669
          cmake: 3.10.2.4988404
          force-avd-creation: false
          emulator-options: -no-snapshot-save -skin 1080x2220 -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          disable-spellchecker: true
          script: |
            sed -i -e 's#DEMO_SHOWCASE_DEBUG_ONLY = false#DEMO_SHOWCASE_DEBUG_ONLY = true#' ./app/src/main/java/com/zoffcc/applications/undereat/corefuncs.java
            ./gradlew build ; ./gradlew installDebug
            adb shell 'pm grant com.zoffcc.applications.undereat android.permission.ACCESS_COARSE_LOCATION'
            adb shell am start -n com.zoffcc.applications.undereat/com.zoffcc.applications.undereat.MainActivity  &
            sleep 60
            adb exec-out screencap -p > ~/android_screen01_${{ matrix.api-level }}.png
            ls -al ~/android_screen01_${{ matrix.api-level }}.png
            adb logcat -d |grep 'UnderEat'
            adb logcat -d > ~/adb_log.txt
            sleep 2

      - name: upload screenshots
        uses: actions/upload-artifact@v4
        with:
          name: linuxscreen_${{ matrix.api-level }}
          path: |
            /home/runner/android_screen*.png

      - name: upload screenshots
        uses: actions/upload-artifact@v4
        with:
          name: adb_log_${{ matrix.api-level }}
          path: |
            /home/runner/adb_log.txt

      - name: Upload to nightly release
        uses: ncipollo/release-action@v1
        if: github.ref == 'refs/heads/master'
        with:
          allowUpdates: true
          tag: nightly
          omitBodyDuringUpdate: true
          omitNameDuringUpdate: true
          prerelease: true
          replacesArtifacts: true
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "/home/runner/android_screen01_${{ matrix.api-level }}.png"

  android-apk:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: ${{ true }}
    steps:
      - uses: actions/checkout@v4

      - name: build artifact for nightly upload
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: |
         pwd
         ./gradlew build
         find . -name '*.apk'
         cp -av ./app/build/outputs/apk/debug/app-debug.apk UnderEat-nightly.apk

      - name: Upload to nightly release
        uses: ncipollo/release-action@v1
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        with:
          allowUpdates: true
          tag: nightly
          omitBodyDuringUpdate: true
          omitNameDuringUpdate: true
          prerelease: true
          replacesArtifacts: true
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "UnderEat-nightly.apk"


